/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Relatorio.java
 *
 * Created on 13/11/2009, 10:07:22
 */

package br.edu.ifrn.gui;

import br.edu.ifrn.dao.RelatorioDAO;
import br.edu.ifrn.dominio.Funcionario;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import br.edu.ifrn.dominio.Relatorio;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2007134010556
 */
public class Relatorio extends javax.swing.JFrame {

    /** Creates new form Relatorio */
    public Relatorio() {
        initComponents();
        listarRelatorios();
    }

    public void listarRelatorios(){
        LinkedList<Relatorio> rel = new LinkedList();
        rel = rdao.selectRelatorio();
        RelatorioDAO rdao = new RelatorioDAO();
        Object[][] relV = new Object[rel.size()][7];
        int pos = 0;
        String descricaoT[] = {"Data","Hora","Cd","Cliente","Administrador","Vendedor","Faturamento"};
        Iterator<Relatorio> it = rdao.iterator();

        while(it.hasNext()){
            Relatorio r = it.next();
            relV[pos][0] = r.getData();
            relV[pos][1] = r.getHora();
            relV[pos][2] = r.getCd();
            relV[pos][3] = r.getCli();
            relV[pos][4] = r.getAdm();
            relV[pos][5] = r.getVend();
            relV[pos][6] = r.getFat();
            pos++;
        }
        
        listaRel.setModel(new DefaultTableModel(relV, descricaoT));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        listaRel = new javax.swing.JTable();

        setTitle("Relatorio do dia " + title);
        setResizable(false);

        listaRel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Quantidade de CDs vendidos", "Gastos totais", "Saldo final"
            }
        ));
        scrollPane.setViewportView(listaRel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private Date data = new Date();
    String formato = "dd/MM/yyyy";
    SimpleDateFormat formatter = new SimpleDateFormat(formato);
    String title = formatter.format(data);

    /**
    * @param args the command line arguments
    */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable listaRel;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    
}
