/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListaVendas.java
 *
 * Created on 13/11/2009, 09:46:36
 */

package br.edu.ifrn.gui;

import br.edu.ifrn.dao.VendaDAO;
import br.edu.ifrn.dominio.Venda;
import java.util.Iterator;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2007134010556
 */
public class ListaVendas extends javax.swing.JFrame {

    /** Creates new form ListaVendas */
    public ListaVendas() {
        initComponents();
        listarVendas();
    }

    public void listarVendas(){
        LinkedList<Venda> vendas = new LinkedList();
        VendaDAO vdao = new VendaDAO();
        vendas = vdao.selectVenda();
        Object[][] vendasV = new Object[vendas.size()][5];
        int pos = 0;
        String descricaoT[] = {"CDs","Quantidade total","Cliente","Vendedor","Preço total"};
        Iterator<Venda> it = vendas.iterator();

        while(it.hasNext()){
            Venda v = it.next();
            vendasV[pos][0] = v.getCDName();
            vendasV[pos][1] = v.getQuantCdsVendidos();
            vendasV[pos][2] = v.getCli();
            vendasV[pos][3] = v.getVend();
            vendasV[pos][4] = v.getPreco() * v.getQuantCdsVendidos();
            pos++;
        }

        listaDeVendas.setModel(new DefaultTableModel(vendasV, descricaoT));


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        listaDeVendas = new javax.swing.JTable();

        setTitle("Lista de Vendas");
        setResizable(false);

        listaDeVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "CDs", "Quantidade total", "Cliente", "Vendedor", "Preço total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane.setViewportView(listaDeVendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable listaDeVendas;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

}
